#!/bin/bash
#
# Update Project Status Script
# Updates the project status in the Technical Architecture file (after Phase 2.2)
# or creates/updates a status file for earlier phases
#
# Usage:
#   ./update-project-status.sh <current-phase> [status-message]
#   ./update-project-status.sh --show
#
# Exit codes:
#   0 = Success
#   1 = Error

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# File paths
PRD_FILE="docs/Project-Technical-Architecture.md"
STATUS_FILE="docs/project-status.md"

# Phase names for display
declare -A PHASE_NAMES=(
    ["1.1"]="Master Concept Refinement"
    ["1.2"]="Brand Kit & Guide Creation"
    ["1.3"]="Service Naming & Domain"
    ["1.4"]="Marketing Foundation"
    ["2.1"]="MVP UX Design"
    ["2.2"]="Technical PRD & Git Structure"
    ["3.1"]="Consistency & Quality Check"
    ["4.1"]="Notion Database Building"
    ["4.2"]="User Approval & Template Selection"
    ["4.3"]="Template Integration"
    ["4.4"]="Stage Architecture Planning"
    ["5.1"]="Architecture Consistency Check"
    ["6.1"]="Stage Execution"
    ["6.2"]="Security Review"
    ["7.1"]="Final Validation & Handoff"
)

# Show current status
show_status() {
    if [[ -f "$PRD_FILE" ]]; then
        echo -e "${BLUE}Status from Technical Architecture:${NC}"
        grep -A 20 "## Project Status" "$PRD_FILE" 2>/dev/null || echo "  No status section found"
    elif [[ -f "$STATUS_FILE" ]]; then
        echo -e "${BLUE}Status from project-status.md:${NC}"
        cat "$STATUS_FILE"
    else
        echo -e "${YELLOW}No status file found yet${NC}"
        echo "  Status tracking begins after Phase 2.2 (Technical PRD)"
        echo "  Or you can create docs/project-status.md manually"
    fi
}

# Update status
update_status() {
    local phase_id="$1"
    local message="${2:-}"
    local timestamp
    timestamp=$(date "+%Y-%m-%d %H:%M")
    
    local phase_name="${PHASE_NAMES[$phase_id]:-Unknown Phase}"
    
    # Build status entry
    local entry="### $timestamp - Phase $phase_id: $phase_name"
    if [[ -n "$message" ]]; then
        entry="$entry"$'\n'"$message"
    fi
    entry="$entry"$'\n'""
    
    # If PRD exists, try to update it
    if [[ -f "$PRD_FILE" ]]; then
        if grep -q "## Project Status" "$PRD_FILE"; then
            # Append to existing status section
            # Find the line with "## Project Status" and insert after it
            local temp_file
            temp_file=$(mktemp)
            # Ensure temp file is cleaned up on script exit or error
            trap "rm -f '$temp_file'" EXIT
            awk -v entry="$entry" '
                /^## Project Status/ {
                    print
                    getline
                    print
                    print entry
                    next
                }
                {print}
            ' "$PRD_FILE" > "$temp_file"
            mv "$temp_file" "$PRD_FILE"
            trap - EXIT  # Clear trap after successful operation
            echo -e "${GREEN}✓ Updated status in Technical Architecture${NC}"
        else
            # Add status section at the end
            {
                echo ""
                echo "---"
                echo ""
                echo "## Project Status"
                echo ""
                echo "$entry"
            } >> "$PRD_FILE"
            echo -e "${GREEN}✓ Created status section in Technical Architecture${NC}"
        fi
    else
        # Create or update status file
        mkdir -p "$(dirname "$STATUS_FILE")"
        
        if [[ ! -f "$STATUS_FILE" ]]; then
            # Create new status file
            {
                echo "# Project Status"
                echo ""
                echo "*Auto-generated by Co-CEO Session*"
                echo ""
                echo "---"
                echo ""
                echo "$entry"
            } > "$STATUS_FILE"
            echo -e "${GREEN}✓ Created $STATUS_FILE${NC}"
        else
            # Append to existing file
            {
                echo "$entry"
            } >> "$STATUS_FILE"
            echo -e "${GREEN}✓ Updated $STATUS_FILE${NC}"
        fi
    fi
    
    # Show what was written
    echo ""
    echo -e "${BLUE}Status entry:${NC}"
    echo "$entry"
}

# Main
main() {
    if [[ $# -eq 0 ]]; then
        echo "Update Project Status Script"
        echo ""
        echo "Usage:"
        echo "  $0 <phase-id> [status-message]"
        echo "  $0 --show"
        echo ""
        echo "Examples:"
        echo "  $0 1.1 \"Master Concept created successfully\""
        echo "  $0 2.2 \"Technical PRD ready, git branches created\""
        echo "  $0 --show"
        exit 0
    fi
    
    case "$1" in
        --show)
            show_status
            ;;
        *)
            if [[ -z "${PHASE_NAMES[$1]:-}" ]]; then
                echo -e "${RED}Unknown phase: $1${NC}" >&2
                echo "Valid phases: ${!PHASE_NAMES[*]}" >&2
                exit 1
            fi
            update_status "$1" "${2:-}"
            ;;
    esac
}

main "$@"
